hint: Pulling without specifying how to reconcile divergent branches is
hint: discouraged. You can squelch this message by running one of the following
hint: commands sometime before your next pull:
hint: 
hint:   git config pull.rebase false  # merge (the default strategy)
hint:   git config pull.rebase true   # rebase
hint:   git config pull.ff only       # fast-forward only
hint: 
hint: You can replace "git config" with "git config --global" to set a default
hint: preference for all repositories. You can also pass --rebase, --no-rebase,
hint: or --ff-only on the command line to override the configured default per
hint: invocation.
From https://github.com/inacioinvita/HP_FT_TM
 * branch            main       -> FETCH_HEAD
Updating 2cc9277..31a7497
Fast-forward
 BALS_trainer.py          |   2 +-
 run_BALS_trainer.job     |  54 +++++------
 run_trainer_CP_mamba.job |  59 ++++++++++++
 trainer_cp2_pt.py        | 229 +++++++++++++++++++++++++++++++++++++++++++++++
 4 files changed, 311 insertions(+), 33 deletions(-)
 create mode 100644 run_trainer_CP_mamba.job
 create mode 100644 trainer_cp2_pt.py
/var/lib/slurm-llnl/slurmd/job222380/slurm_script: line 24: /etc/profile.d/modules.sh: No such file or directory
/var/lib/slurm-llnl/slurmd/job222380/slurm_script: line 25: module: command not found
/var/lib/slurm-llnl/slurmd/job222380/slurm_script: line 26: module: command not found

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/home/ivieira/mambaforge/lib/python3.12/site-packages/conda/exception_handler.py", line 18, in __call__
        return func(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^
      File "/home/ivieira/mambaforge/lib/python3.12/site-packages/conda/cli/main.py", line 87, in main_sourced
        print(activator.execute(), end="")
              ^^^^^^^^^^^^^^^^^^^
      File "/home/ivieira/mambaforge/lib/python3.12/site-packages/conda/activate.py", line 238, in execute
        response = getattr(self, self.command)()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/ivieira/mambaforge/lib/python3.12/site-packages/conda/activate.py", line 200, in activate
        builder_result = self.build_activate(self.env_name_or_prefix)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/ivieira/mambaforge/lib/python3.12/site-packages/conda/activate.py", line 367, in build_activate
        return self._build_activate_stack(env_name_or_prefix, False)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/ivieira/mambaforge/lib/python3.12/site-packages/conda/activate.py", line 457, in _build_activate_stack
        deactivate_scripts = self._get_deactivate_scripts(old_conda_prefix)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/ivieira/mambaforge/lib/python3.12/site-packages/conda/activate.py", line 810, in _get_deactivate_scripts
        for entry in os.scandir(join(prefix, "etc", "conda", "deactivate.d"))
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "<frozen posixpath>", line 76, in join
    TypeError: expected str, bytes or os.PathLike object, not NoneType

`$ /home/ivieira/mambaforge/bin/conda shell.posix activate my-pip-env`

  environment variables:
                 CIO_TEST=<not set>
                CONDA_EXE=/home/ivieira/mambaforge/bin/conda
         CONDA_PYTHON_EXE=/home/ivieira/mambaforge/bin/python
               CONDA_ROOT=/home/ivieira/mambaforge
              CONDA_SHLVL=1
           CURL_CA_BUNDLE=<not set>
               LD_PRELOAD=<not set>
                     PATH=/home/ivieira/mambaforge/bin:/home/ivieira/.local/bin:/home/ivieira/.l
                          ocal/bin:/home/ivieira/.local/bin:/usr/local/bin:/usr/bin:/bin:/usr/lo
                          cal/games:/usr/games
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : None
            shell level : 1
       user config file : /home/ivieira/.condarc
 populated config files : /home/ivieira/mambaforge/.condarc
          conda version : 24.11.2
    conda-build version : not installed
         python version : 3.12.7.final.0
                 solver : libmamba (default)
       virtual packages : __archspec=1=icelake
                          __conda=24.11.2=0
                          __cuda=12.5=0
                          __glibc=2.31=0
                          __linux=5.10.0=0
                          __unix=0=0
       base environment : /home/ivieira/mambaforge  (writable)
      conda av data dir : /home/ivieira/mambaforge/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : /home/ivieira/mambaforge/pkgs
                          /home/ivieira/.conda/pkgs
       envs directories : /home/ivieira/mambaforge/envs
                          /home/ivieira/.conda/envs
               platform : linux-64
             user-agent : conda/24.11.2 requests/2.32.3 CPython/3.12.7 Linux/5.10.0-33-amd64 debian/11.11 glibc/2.31 solver/libmamba conda-libmamba-solver/24.9.0 libmambapy/1.5.9
                UID:GID : 10448:100
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.
If you suspect this error is being caused by a malfunctioning plugin,
consider using the --no-plugins option to turn off plugins.

Example: conda --no-plugins install <package>

Alternatively, you can set the CONDA_NO_PLUGINS environment variable on
the command line to run the command without plugins enabled.

Example: CONDA_NO_PLUGINS=true conda install <package>

Requirement already satisfied: torch in /home/ivieira/mambaforge/lib/python3.12/site-packages (2.5.1+cu121)
ERROR: Could not find a version that satisfies the requirement ctranslate2==4.3.0 (from versions: 3.19.0, 3.20.0, 3.21.0, 3.22.0, 3.23.0, 3.24.0, 4.0.0, 4.1.0, 4.2.1, 4.3.1, 4.4.0, 4.5.0)
ERROR: No matching distribution found for ctranslate2==4.3.0
Traceback (most recent call last):
  File "/home/ivieira/chicago2/HP_FT_TM/sage_train_inf_eval.py", line 4, in <module>
    import torch
  File "/home/ivieira/mambaforge/lib/python3.12/site-packages/torch/__init__.py", line 367, in <module>
    from torch._C import *  # noqa: F403
    ^^^^^^^^^^^^^^^^^^^^^^
ImportError: libcudnn.so.9: cannot open shared object file: No such file or directory
